### ISSUE TITLE
Testing unit for the database API

### ISSUE THREAD

**Issue by Mysterise** [csesoc/notangles#16]
Setup a testing unit for the DB API introduced in #10 so we can validate our class data are correct.

Suggesting to use the ~Mocha~ Jest framework.

**Comment by ecl1ipse** [comment]
I'm blocked on this issue because when I npm run test, it says "TypeError: Cannot read property 'database' of undefined". This seems to be an issue specific to jest since copying the code in db.ts to dbApi.test.ts has the same error message when running db.ts works fine.
<img width="976" alt="Screen Shot 2019-07-31 at 10 52 34 am" src="https://user-images.githubusercontent.com/38648975/62175518-5d5c6480-b381-11e9-9852-753523769d21.png">
@Skithy
